spring.application.name=java-backend-performance-lab

management.endpoints.web.exposure.include=health

lab.auth.session-ttl=30s
lab.auth.new-session-delay=0s

spring.datasource.url=${LAB_DB_URL:jdbc:postgresql://localhost:5432/performance_lab}
spring.datasource.username=${LAB_DB_USERNAME:performance_lab}
spring.datasource.password=${LAB_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
